# Generated by Django 5.1.3 on 2024-12-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('mail', models.CharField(max_length=100, unique=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('hostel', models.CharField(max_length=10)),
                ('room', models.IntegerField()),
            ],
        ),
    ]
