# Generated by Django 5.1.3 on 2024-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0002_book_parent_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_parent',
            name='available_copies',
            field=models.IntegerField(),
        ),
    ]
