# Generated by Django 5.1.3 on 2024-12-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0005_alter_book_parent_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_parent',
            name='available_copies',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='book_parent',
            name='total_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
