# Generated by Django 5.1.3 on 2024-12-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0007_alter_book_parent_available_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_parent',
            name='cover_image',
            field=models.ImageField(default='book_covers/no-cover.jpg', upload_to='book_covers/'),
        ),
    ]
