# Generated by Django 5.1.3 on 2024-12-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0008_alter_book_parent_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_parent',
            name='cover_image',
            field=models.ImageField(default='book_covers/no-image.jpg', upload_to='book_covers/'),
        ),
    ]
