# Generated by Django 5.1.3 on 2024-12-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0009_alter_book_parent_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_parent',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
