# Generated by Django 5.1.3 on 2024-12-24 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0011_librarysettings_book_borrow_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='feedback_images/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('rated_at', models.DateTimeField(auto_now_add=True)),
                ('parent_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='libapp.book_parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.student')),
            ],
        ),
    ]
