# Generated by Django 5.1.3 on 2024-12-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0013_librarysettings_fee_compound'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dues',
            field=models.IntegerField(default=0),
        ),
    ]
