# Generated by Django 5.1.3 on 2024-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0014_student_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_borrow',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
