# Generated by Django 5.1.3 on 2024-12-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0015_alter_book_borrow_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_borrow',
            name='borrow_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
