# Generated by Django 5.1.3 on 2024-12-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0017_alter_student_dues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dues',
            field=models.IntegerField(default=0),
        ),
    ]
