# Generated by Django 5.1.3 on 2024-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0018_alter_student_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_borrow',
            name='penalty',
            field=models.IntegerField(default=0),
        ),
    ]
