# Generated by Django 5.1.3 on 2025-01-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0019_book_borrow_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='libapp.book_parent'),
        ),
    ]
